services:
  mysql:
    image: mysql:8.0
    container_name: jml-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: jml
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: jml-backend
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: jml
      DB_USERNAME: root
      DB_PASSWORD:
    depends_on:
      - mysql

volumes:
  db_data:
  vendor_data:
